home/urls.py
from django.conf.urls import url
from .api import views as api_views
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$',  views.index, name='home'),
    url(r'^test/$',  views.test, name='home'),
    url(r'^feedback/$',  views.feedback, name='feedback'),
    url(r'^question/$',  views.question_upload, name='question_upload'),
    url(r'^about/$',  views.about, name='about'),
    url(r'^Members/$',  views.members, name='members'),
    url(
        regex=r'^api/get-username/$',
        view=api_views.get_username,
    ),
    url(
        regex=r'^api/userlist/$',
        view=api_views.get_user_list,
    ),
    url(
        regex=r'^api/userprofile/$',
        view=api_views.get_user_profile,
    ),
    url(
        regex=r'^api/event-list/$',
        view=api_views.get_events,
    ),
    url(
        regex=r'^api/current-user-detail/$',
        view=api_views.current_user_detail,
    ),
    url(
        regex=r'^api/userprofile/(?P<pk>\d+)/$',
        view=api_views.get_user_profile,
    ),
]
   

skflite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls import url
from home import views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'social/', include('social.urls', namespace = "social")),
    path('admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf.urls import url
from . import views
app_name = "social" 
urlpatterns = [
    url(r'^Post/$',  views.user_post, name='post'),
    url(r'^Post/delete/(?P<pk>[0-9]+)$',  views.delete_post, name='delete_post'),
    url(r'^Event/$',  views.events, name='events'),
    url(r'^Event/delete/(?P<pk>[0-9]+)$',  views.delete_events, name='delete_events'),
    url(r'^News/$',  views.news, name='news'),
   
]
    

social/models.py
from django.db import models
from django.contrib.auth.models import User

class UserPost(models.Model):
    posted_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    posted_date = models.DateTimeField(auto_now_add=True)
    posted_update_date = models.DateTimeField(auto_now=True)
    user_post_description = models.TextField(blank=True)

class Comment(models.Model):
    post_id = models.IntegerField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    text = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)
   
    def __str__(self):
        return self.text

class Likes(models.Model):
    post_id = models.IntegerField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    likes = models.CharField(max_length=50, default='like')
    like_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.likes
       

class News(models.Model):
    title = models.CharField(max_length=200)
    news_detail = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title 

class Event(models.Model):
    title = models.CharField(max_length=200)
    event_class = models.CharField(max_length=200, default='bg-blue')
    event_detail = models.TextField(blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return self.title 

social/forms.py
from django import forms
from .models import UserPost, News, Event
from social.widgets import MediumEditorTextarea


class UserPostForm(forms.ModelForm):
    class Meta:
        model = UserPost
        fields = ('user_post_description',)   
        widgets = {
            'user_post_description': MediumEditorTextarea,       
        }


class NewsForm(forms.ModelForm):

    class Meta:
        model = News
        exclude = ('date', )
        widgets = {
            'news_detail': MediumEditorTextarea,
        }

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ('title', 'event_class', 'event_detail', 'start_date','end_date',)   
        widgets = {
            'event_detail': forms.Textarea(attrs={      
            'required': True, 
            'placeholder': 'Event detail'
        }),
            'title': forms.TextInput(attrs={      
            'required': True, 
            'placeholder': 'Title'
        }),
            'start_date': forms.TextInput(attrs={      
                'required': True, 
                'placeholder': 'Start date'
        }),
            'end_date': forms.TextInput(attrs={      
                'required': True, 
                'placeholder': 'End date'
        }),
            'event_class': forms.HiddenInput()       
        }   

social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from skflite import settings
from .forms import UserPostForm, NewsForm, EventForm
from .models import UserPost, News, Event


@login_required
def user_post(request):
    if request.method == 'POST':
        form = UserPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = UserPostForm()
    return render(request, "home.html", {
        'form': form
    })

def delete_post(request, pk):
    post = get_object_or_404(UserPost, pk=pk)
    post.delete()
    return redirect('/')


@login_required
def news(request):
    form = NewsForm()
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/social/News')
        else:
            return redirect('/social/News')
    else:
        context = {
            'form': form,
            'newses': News.objects.all().order_by('-date'),
        }
    return render(request, "social/news.html", context)
@login_required
def events(request):
    form = EventForm()
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/social/Event')
        else:
            print("envalid")
            return redirect('/social/Event')
    else:
        context = {
            'form': form, 
            'events': Event.objects.all().order_by('-start_date')     
        }
    return render(request, "social/events.html", context)

def delete_events(request, pk):
    enents = get_object_or_404(Event, pk=pk)
    enents.delete()
    return redirect("/social/Event")

templates/social/events.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "css/fullcalendar.min.css" %}">
<link rel="stylesheet" href="{% static "css/fullcalendar.print.min.css" %} media="print"">
{% endblock css %}

{% block content %}

<section class="content">
    <div class="row">
      <div class="col-md-3">
        <div class="box box-solid">
          <div class="box-header with-border">
            <h4 class="box-title">YOUR EVENTS</h4>
          </div>
          <div class="box-body">
            <div id="external-events">
              {% for event in events %}
              <div class="external-event " style="background-color:{{event.event_class}}">{{event.title}}
                  <a href="{% url 'social:delete_events' event.pk %}">Delete</a>
              </div>
              {% endfor%}
              <div class="checkbox">
                <label for="drop-remove">
                  <input type="checkbox" id="drop-remove">
                  remove after drop
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="box box-solid">
          <div class="box-header with-border">
            <h3 class="box-title">Create Event</h3>
          </div>
          <div class="box-body">
            <div class="btn-group" style="width: 100%; margin-bottom: 10px;">
              <ul class="fc-color-picker" id="color-chooser">
                <li><a class="text-aqua" data="bg-aqua" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-blue" data="bg-blue" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-light-blue" data="bg-light-blue" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-teal" data="bg-teal" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-yellow" data="bg-yellow" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-orange" data="bg-orange" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-green" data="bg-green" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-lime" data="bg-lime" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-red" data="bg-red" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-purple" data="bg-purple" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-fuchsia" data="bg-fuchsia" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-muted" data="bg-muted" href="#"><i class="fa fa-square"></i></a></li>
                <li><a class="text-navy" data="bg-navy" href="#"><i class="fa fa-square"></i></a></li>
              </ul>
            </div>
            <div class="input-group">
              <form method="post" enctype="multipart/form-data" class="event_form">
                  {% csrf_token %}
                  {{ form.title }}            
                  {{ form.event_class }}
                  {{ form.event_detail }}
                  {{ form.start_date }}            
                  {{ form.end_date }}  
                  <button id="add-new-event" type="submit" class="btn btn-primary btn-flat">Add</button> 

              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="box box-primary">
          <div class="box-body no-padding">
            <div id="calendar"></div>
          </div>
        </div>
      </div>
    </div>
  </section>

<script>
  var evnt=[];
$(document).ready(function () {


    $.ajax({
        url: "/api/event-list",
        type: "Get",
        success: function (data) {
          var evnt=data.events;               
          function init_events(ele) {
            ele.each(function () {
              var eventObject = {
                title: $.trim($(this).text()) 
              }   
              $(this).data('eventObject', eventObject)     
            })
          }
    init_events($('#external-events div.external-event'))
   
    var date = new Date()
    var d    = date.getDate(),
        m    = date.getMonth(),
        y    = date.getFullYear()
    
    $('#calendar').fullCalendar({
      header    : {
        left  : 'prev,next today',
        center: 'title',
        right : 'month,agendaWeek,agendaDay'
      },
      buttonText: {
        today: 'today',
        month: 'month',
        week : 'week',
        day  : 'day'
      },
      events    : evnt,
      editable  : false,
      droppable : false, 
     
    })
  },    
  });
    $('#color-chooser > li > a').click(function (e) {
      e.preventDefault()
      currColor = $(this).attr("data");
      currColors = $(this).css('color')
      $('#id_event_class').val(currColors)
      var currColors = '#3c8dbc'
      currColors = $(this).css('color')
      $('#add-new-event').css({ 'background-color': currColors, 'border-color': currColors })
    })  
    $(".fc-content ").bind("click",function(){
  alert("File is changed.");
}); 
  });
  $(function () {
    flatpickr("#id_start_date", {
      dateFormat: "Y-m-d H:i",
      enableTime: true
    });
    flatpickr("#id_end_date", {
      dateFormat: "Y-m-d H:i",
      enableTime: true
    });
  });


  $(".fc-event-container").click(function(){
      alert("zdjk")
    $('#myModal').modal('toggle');
  });
</script>
{% endblock %}

templates/social/news.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
                  
<section class="content" ng-app="myApp">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Please share latest news that can help others</h3>
                </div>
                <div class="box-body">
                    <form method="post" enctype="multipart/form-data" class="news_form">
                        {% csrf_token %}
                        <label>News title</label>
                        {{ form.title }}
                        {{ form.news_detail }}
                        <button class="btn btn-block btn-info btn-flat" type="submit">SUBMIT</button>                        
                    </form>
                </div>  
                <div class="tab">
                    <button class="tablinks" onclick="openCity(event, 'London')">Google news</button>
                    <button class="tablinks" onclick="openCity(event, 'Paris')">Site news</button>
                    <button class="tablinks" onclick="openCity(event, 'Tokyo')">Weather</button>
                </div>
                  
                <div id="London" class="tabcontent">                 
                    {% verbatim %} 
                    <div class="box box-widget news_img"  ng-controller="newscontroller" ng-init="init();"> 
                        <div ng-repeat="list in getnews">
                            <div ng-if="list.title" class="box-header with-border">
                            <a href="{{list.url}}"> <h3> {{list.title}}</h3></a>  
                            </div>
                            <div class="box-body">
                                <div class="col-sm-6">
                                    <h4 ng-if="list.description">{{list.description}}</h4><br/>                                                          
                                <span ng-if="list.author">Author: {{list.author}} </span>
                                <h4> Published At: {{list.publishedAt | date :  "dd.MM.y"}}</h4>
                                <h3 ng-if="list.source.name">{{list.source.name}}</h3>
                                
                                </div>
                                <div ng-if="list.urlToImage" class="col-sm-6">
                                    <img src="{{list.urlToImage}}" width="400", height="300"/>
                                </div>                            
                            </div>
                        </div>          
                    </div>
                    {% endverbatim %}
                </div>
                <div id="Tokyo" class="tabcontent">
                        <div class="box-body">
                            <div my-map=""></div>
                            <div id="map" style="height:300px"></div>
                            <script src="{% static "js/map.js" %}"></script>
                            <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCX03rRy8YH_WKXN523KvPGFA1E1uBQbQA&callback=initMap"></script>
                            {% verbatim %}
                            <div class="col-sm-12 weather_info" ng-controller="weathercontroller" ng-init="init();">          
                                <div class="col-sm-4">
                                    <table style="width:100%">
                                        <tr><th><h4>Wind information</h4></th></tr>
                                        <tr>
                                            <td>speed :</td><td>{{getweather.wind.speed}} &nbsp; meter/sec</td>                    
                                        </tr>
                                        <tr>
                                            <td>Degree :</td><td>{{getweather.wind.deg}} &nbsp; degree</td>                                                                                  
                                        </tr>
                                        <tr>
                                            <td>Gust :</td><td>{{getweather.wind.deg}} &nbsp; degree</td>  
                                        </tr>
                                    </table>                                                                         
                                </div>
                                <div class="col-sm-4">
                                    <table style="width:100%">
                                        <tr><th><h4>Tempreture information</h4></th></tr>
                                        <tr>
                                            <td>temp :</td><td>{{getweather.main.temp-273.15 | number:2}}&nbsp; &#8451;</td>                    
                                        </tr>
                                        <tr>
                                            <td>temp_min :</td><td>{{getweather.main.temp_min-273.15 | number:2}} &nbsp; &#8451;</td>                                                                                  
                                        </tr>
                                        <tr>
                                            <td>temp_max :</td><td>{{getweather.main.temp_max-273.15 | number:2}}&nbsp;	&#8451;</td>  
                                        </tr>
                                        <tr>
                                            <td>pressure :</td><td>{{getweather.main.pressure}} &nbsp; hPa</td>  
                                        </tr>
                                        <tr>
                                            <td>humidity :</td><td>{{getweather.main.humidity}} &nbsp;%</td>  
                                        </tr>
                                    </table>                                                             
                                </div>
                                <div class="col-sm-4">
                                        <strong>{{getweather.name}} </strong>  
                                    <div ng-repeat="weather in weatherinfo">                                       
                                        <img src="/static/Images/{{weather.icon}}.png" width="100",height="100"/>   
                                        <h4> {{weather.description}}</h4>                                 
                                    </div>
                                </div>
                            </div> 
                            {% endverbatim %}              
                        </div>      
                    </div>                
                <div id="Paris" class="tabcontent">
                    {% for news in newses %}   
                    <div class="box box-widget">   
                        <div class="box-header with-border">
                            <h3>{{news.title}}</h3>
                        </div>
                        <div class="box-body">
                            {{news.news_detail |safe}}
                        </div>
                    </div>
                    {%endfor%}
                </div>                                 
                <script>
                  function openCity(evt, cityName) {
                      var i, tabcontent, tablinks;
                      tabcontent = document.getElementsByClassName("tabcontent");
                      for (i = 0; i < tabcontent.length; i++) {
                          tabcontent[i].style.display = "none";
                      }
                      tablinks = document.getElementsByClassName("tablinks");
                      for (i = 0; i < tablinks.length; i++) {
                          tablinks[i].className = tablinks[i].className.replace(" active", "");
                      }
                      document.getElementById(cityName).style.display = "block";
                      evt.currentTarget.className += " active";
                  }
                </script>
            </div>
        </div>
    </div>
</section>

{% endblock %}



 

templates/social/user_post.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Post</button>
    </div>
</form>