accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
LoginView,
LogoutView,
PasswordResetView,
PasswordResetConfirmView,
PasswordResetDoneView,
PasswordResetCompleteView,
PasswordChangeView,
PasswordChangeDoneView,
)

from .views import edit_profile
from . import views

app_name = "accounts"
urlpatterns = [
    url(r'settings/accounts/$', views.accounts_settings, name='accounts_settings'),
    url(r'settings/general/$', views.general_settings, name='general_settings'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': '/accounts/login'}, name='logout'),
    url(r'^user/profile/$', views.profile, name='Profile'),
    url(r'^user/profile/friend/(?P<pk>.+)/$', views.friend_profile, name='Friend_Profile'),
    url(r'^user/profile/add/$', views.add_user_info, name='add_user_info'),
    url(r'^user/profile/update/$', views.update_user_info, name='update_user_info'),
    url(r'^profile/edit/$', views.edit_profile, name='Profile-update'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^password-reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^activate/(?P<uidb64>.+)/(?P<token>.+)/$', views.activate, name='activate'),
    url(r'connect/(?P<operation>.+)/(?P<pk>.+)/$', views.change_friend, name='change_friend'),
]

home/urls.py
from django.conf.urls import url
from .api import views as api_views
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$',  views.index, name='home'),
    url(r'^test/$',  views.test, name='home'),
    url(r'^feedback/$',  views.feedback, name='feedback'),
    url(r'^question/$',  views.question_upload, name='question_upload'),
    url(r'^about/$',  views.about, name='about'),
    url(r'^Members/$',  views.members, name='members'),
    url(
        regex=r'^api/get-username/$',
        view=api_views.get_username,
    ),
    url(
        regex=r'^api/userlist/$',
        view=api_views.get_user_list,
    ),
    url(
        regex=r'^api/userprofile/$',
        view=api_views.get_user_profile,
    ),
    url(
        regex=r'^api/event-list/$',
        view=api_views.get_events,
    ),
    url(
        regex=r'^api/current-user-detail/$',
        view=api_views.current_user_detail,
    ),
    url(
        regex=r'^api/userprofile/(?P<pk>\d+)/$',
        view=api_views.get_user_profile,
    ),
]
   

skflite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls import url
from home import views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'social/', include('social.urls', namespace = "social")),
    path('admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

def get_upload_image_name(instance, filename):

    new_filename = str(instance.user.id) + ".jpg"
    return 'user/{0}'.format(new_filename)



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profession = models.CharField(max_length=30, blank=True)
    bio = models.CharField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    skils = models.CharField(max_length=30, blank=True)
    education = models.CharField(max_length=30, blank=True)
    edu_center = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    linkedin_profile = models.URLField(blank=True)
    twitter_profile = models.URLField(blank=True)
    facebook_profile = models.URLField(blank=True)
    image = models.ImageField(upload_to=get_upload_image_name , null=True, blank=True)

# class FriendsData(models.Model):
#     fromUserId = models.CharField(max_length=30, blank=True)
#     toUserId = models.CharField(max_length=30, blank=True)
#     status = models.BooleanField(default=False)
#     requestDate = models.DateTimeField(auto_now_add=True)
#     conformDate = models.DateTimeField(null=True, blank=True)
#     @classmethod
#     def addFriends(cls, current_user, new_friend):
#         print(current_user)
#         print(new_friend)
#         friendobj = FriendsData(fromUserId=current_user, toUserId=new_friend )
#         friendobj.save()
#     @classmethod
#     def removeFriends(cls, current_user, new_friend):
#         friend, created = cls.objects.get_or_create(
#             current_user=current_user
#         )
#         friend.users.add(new_friend)

class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.SET_NULL)
    status = models.BooleanField(default=False)
    requestDate = models.DateTimeField(auto_now_add=True)
    conformDate = models.DateTimeField(null=True, blank=True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def conform_friend(cls, current_user, new_friend):
        f = Friend.objects.get(current_user=current_user)
        f.status = True
        f.save
    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

accounts/forms.py
from django import forms
from django.db import models
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profession', 'bio', 'location', 'birth_date', 'skils', 'education', 'edu_center', 'linkedin_profile', 'facebook_profile', 'twitter_profile', 'birth_date', 'image')

class ProfileUpdateForm(UserChangeForm):
    class Meta:
        model= User
        fields = ('first_name', 'last_name', 'email', 'password')
        labels ={
           'first_name': 'First Name',
           'last_name': 'Last Name',
           'email': 'Your email',
        }

class UpdateProfile(forms.ModelForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-sm-2'
    helper.field_class = 'col-sm-4'
    helper.layout = Layout(
        Field('username', css_class='input-sm'),
        Field('email', css_class='input-sm'),
        Field('first_name', css_class='input-sm'),
        Field('last_name', css_class='input-sm'),
        FormActions(Submit('Update', 'Update', css_class='btn-primary'))
    )
 
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
        return email

    def save(self, commit=True):
        user = super(UpdateProfile, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model= User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        labels ={
           'username': 'Your username',
           'first_name': 'First Name',
           'last_name': 'Last Name',
           'email': 'Your email',
           'password1': 'Your password',
           'password2': 'Please confirm your password'

        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['first_name']
        user.email = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

accounts/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UpdateProfile, UserInfoForm
from django.contrib.auth import update_session_auth_hash
from .forms import RegistrationForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from skflite import settings
from django.core.mail import EmailMessage
from .models import Friend, Profile

#------------------------------------------------------------------------------------------

def accounts_settings(request):
    return render(request, "accounts/account_settings.html")

def general_settings(request):
    return render(request, "accounts/general_settings.html")

#-------------------------------------------------------------------------------------------
def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        username = request.POST.get('username')
        if User.objects.filter(username=username).exists():
            messages.add_message(request, messages.INFO, 'This username is allready exist')
            form = RegistrationForm()
            return redirect('/accounts/signup/')
        else:
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = True
                user.save()
                current_site = get_current_site(request)
                subject = 'Activate your LIFEBOOK account.'
                message = render_to_string('acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': user.pk,
                    'token':account_activation_token.make_token(user),
                })
                from_email = settings.EMAIL_HOST_USER
                to_email = form.cleaned_data.get('email')
                msg = EmailMessage(subject, message, from_email, [to_email])
                msg.content_subtype = "html"
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                user = authenticate(username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('/') 
                # msg.send()      
                # return render(request, 'accounts/signup_conform.html') 
                                            
            else:
                form = RegistrationForm()
                return render(request, 'accounts/signup.html', {'form': form})
    else:
        form = RegistrationForm()
    return render(request, 'accounts/signup.html', {'form': form})

#---------------------------------------------------------------------------------------------

def activate(request, uidb64, token):
    uid = uidb64
    user = User.objects.get(pk=uid)
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.add_message(request, messages.INFO, 'Thank you for your email confirmation.')
        return redirect('/')
    else:
        return HttpResponse('Activation link is invalid!')
#---------------------------------------------------------------------------------------------
@login_required
def edit_profile(request):
    if request.method == 'POST':    
        form = ProfileUpdateForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return redirect('accounts/profile/edit/')
    else:
        form = ProfileUpdateForm(instance = request.user)
       
    return render(request, 'accounts/edit_profile.html', {'form':form})

#---------------------------------------------------------------------------------------------
@login_required
def add_user_info(request):
    if request.method == 'POST':    
        form = UserInfoForm(request.POST, request.FILES)
        if form.is_valid():
            user_info = form.save(commit=False)
            user_info.user = request.user
            user_info.save()
            messages.add_message(request, messages.INFO, 'Congratulations yor information has been added to your profile')
            return redirect('/accounts/user/profile/')
        else:
            messages.add_message(request, messages.INFO, 'Something wrong')
            return redirect('/accounts/user/profile/add/')
    else:
        form = UserInfoForm()
       
    return render(request, 'accounts/user_info_update.html', {'form':form})


#---------------------------------------------------------------------------------------------
@login_required
def update_user_info(request):
    if request.method == 'POST':    
        form = UserInfoForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Congratulations your profile hase been updated')
            return redirect('/accounts/user/profile/')
        else:
            messages.add_message(request, messages.INFO, 'Something wrong')
            return redirect('/accounts/user/profile/update/')
    else:
        form = UserInfoForm(instance=request.user.profile)
       
    return render(request, 'accounts/user_info_update.html', {'form':form})

#--------------------------------------------------------------------------------------------
@login_required
def profile(request):
    user = request.user
    if (Friend.objects.filter(current_user=request.user)).exists():
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
    else:
        friends=[]
    args = {
        'user': user,
        'friend': friends
    }    
    return render(request, 'accounts/profile.html', args)

#--------------------------------------------------------------------------------------------
@login_required
def friend_profile(request, pk=None):
    user = User.objects.filter(pk=pk)
    users = User.objects.get(pk=pk)
    if (Friend.objects.filter(current_user=users)).exists():
        friend = Friend.objects.get(current_user=users)
        friends = friend.users.all()
    else:
        friends=[]
    args = {
        'user': user,
        'friend': friends
    }    
    return render(request, 'accounts/friend_profile.html', args)  
#-----------------------------------------------------------------------------------------------
@login_required
def change_password(request):
    args = {}
    if request.method == 'POST':    
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('/Home/')
        else:
            return redirect('accounts/change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args['form'] = form
    return render(request, 'accounts/change_password.html', args)

#-----------------------------------------------------------------------------------------------

def change_friend(request, operation, pk):
    new_friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, new_friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, new_friend)
    elif operation == 'conform':
        Friend.conform_friend(request.user, new_friend)
    return redirect('/')

# def addFriend(request, operation, pk):
#     new_friend = User.objects.get(pk=pk)
#     if operation == 'add':
#         FriendsData.addFriends(request.user, new_friend)
#     elif operation == 'remove':
#         FriendsData.removeFriends(request.user, new_friend)
#     return redirect('/')

templates/accounts/account_settings.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content">
    <div class="custom-container">
        <div class="row">
            <div class="col-sm-12">
                <div class="col-sm-4">
                    <a href="/accounts/change-password/">Change Password</a>
                    
                </div>
                <div class="col-sm-6"></div>
            </div>
        </div>  
    </div>    
</div>


{% endblock %}

templates/accounts/login.html
{% extends "accounts/accounts.html" %}
{% block content %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="post" class="login100-form validate-form">            
                {% csrf_token %}           
					<span class="login100-form-title p-b-43">
                        <div class="text-shadow-normal" >
                            <h2>Login to continue</h2>
                        </div>					
					</span>
					<span class="error-message">{{ form.non_field_errors }}</span>
					
					<div class="wrap-input100 validate-input">
                        {{ form.username }}
						<span class="focus-input100"></span>
						<span class="label-input100">Username</span>
					</div>		
					<div class="wrap-input100 validate-input">
                        {{ form.password }}		
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>
					<div class="flex-sb-m w-full p-t-3 p-b-32">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>
						<div>
							<a href="{% url 'accounts:password_reset' %}" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>					
					<div class="text-center p-t-46 p-b-20">
                        <p>
                            Not a member yet ?
                        </p>
                        <a href="{% url 'accounts:signup' %}" class="to_register">Join us</a>
					</div>
					<div class="login100-form-social flex-c-m">
						<a href="#" class="login100-form-social-item flex-c-m bg1 m-r-5">
							<i class="fa fa-facebook-f" aria-hidden="true"></i>
						</a>
						<a href="#" class="login100-form-social-item flex-c-m bg2 m-r-5">
							<i class="fa fa-twitter" aria-hidden="true"></i>
						</a>
					</div>
				</form>
				<div class="login100-more" style="background-image: url('/static/Images/bg-01.jpg');">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/accounts/logout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Logout</title>
</head>
<body>
 
    <p>yor reay logout</p>
</body>
</html>

templates/accounts/signup.html
{% extends "accounts/accounts.html" %}
{% block content %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="post" class="login100-form vaalidte-form">            
                {% csrf_token %}           
					<span class="login100-form-title p-b-43">
                        <div class="text-shadow-normal" >
                            <h2>Sign Up</h2>
                        </div>					
					</span>
					<span class="error-message">{{ form.non_field_errors }}</span>
					
					<div class="wrap-input100 validate-input">
                        {{ form.username }}
						<span class="focus-input100"></span>
						<span class="label-input100">{{ form.username.label }}</span>
                    </div>	
                    <div class="wrap-input100 validate-input">
                        {{ form.first_name }}
                        <span class="focus-input100"></span>
                        <span class="label-input100">{{ form.first_name.label }}</span>
                    </div>
                    <div class="wrap-input100 validate-input">
                        {{ form.last_name }}
                        <span class="focus-input100"></span>
                        <span class="label-input100">{{ form.last_name.label }}</span>
                    </div>
                    <div class="wrap-input100 validate-input">
                        {{ form.email }}
                        <span class="focus-input100"></span>
                        <span class="label-input100">{{ form.email.label }}</span>
                    </div>
                    <div class="wrap-input100 validate-input">
                        {{ form.password1 }}
                        <span class="focus-input100"></span>
                        <span class="label-input100">{{ form.password1.label }}</span>
                    </div>	
					<div class="wrap-input100 validate-input">
                        {{ form.password2 }}		
						<span class="focus-input100"></span>
						<span class="label-input100">{{ form.password2.label }}{{ form.password2.errors }}</span>
					</div>		
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign Up
						</button>
					</div>					
					<div class="text-center p-t-46 p-b-20">
                        <p>
                            Allready a member?
                        </p>
                        <a href="{% url 'accounts:login' %}" class="to_register">Sign In</a>
					</div>			
				</form>
				<div class="login100-more" style="background-image: url('/static/Images/bg-01.jpg');">
				</div>
			</div>
		</div>
    </div>
{% endblock %}

templates/accounts/user_info_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    label{
        color: #cccccc;
        padding-top: 10px;
    }
    .thumbnail_container .close {
  position: absolute;
  top: 15px;
  right: 0px;
}

.thumbnail_container {
  position: relative;
  background: #d6d6d6;
  display: table;
  padding: 5px;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.thumbnail_container img {
  display: table-cell;
  height: 50px;
  width: 50px
}

.thumbnail_container span {
  display: table-cell;
  vertical-align: middle;
  text-align: left;
}
/* .image_field{
    background-color: #b0cfae;
    padding: 10px;
    width: 350px;
    color: #ffff;
}
.image_field a{
    color: #ffff
}
.image_field label{
    color: #ffff
} */
input[type=file] {
    display: none;
}
.image_btn{
    font-size: 30px;
}
</style>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <form method="post" class="login" enctype="multipart/form-data">
                        {% csrf_token %}           
                        <div class="form-group">
                            <label>{{ form.profession.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-map-marker"></i>
                                </div>
                                {{ form.profession }}
                            </div>
                            <label>{{ form.location.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-map-marker"></i>
                                </div>
                                {{ form.location }}
                            </div>
                            <label>{{ form.skils.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-puzzle-piece"></i>
                                </div>
                                {{ form.skils }}
                            </div>
                            <label>{{ form.education.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-mortar-board"></i>
                                </div>
                                {{ form.education }}
                            </div>
                            <label>{{ form.edu_center.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-university"></i>
                                </div>
                                {{ form.edu_center }}
                            </div>
                            <label>{{ form.linkedin_profile.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-linkedin"></i>
                                </div>
                                {{ form.linkedin_profile }}                               
                            </div>
                            <label>{{ form.twitter_profile.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-twitter"></i>
                                </div>
                                {{ form.twitter_profile }}
                            </div>
                            <label>{{ form.facebook_profile.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-facebook"></i>
                                </div>
                                {{ form.facebook_profile }}                              
                            </div>
                            <label>{{ form.birth_date.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                {{ form.birth_date }}                           
                            </div>
                            <label>{{ form.bio.label }}</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-pencil-square-o"></i>
                                </div>
                                {{ form.bio }}                         
                            </div>     
                            <div class="image_field">
                                <label for="{{ form.image.id_for_label }}" class="fa fa-camera image_btn">Chose image</label>
                                {{ form.image.errors }}
                                {{ form.image }}
                            </div>              
                        </div>                      
                        <input type="submit" class="btn btn-block btn-info btn-flat" value="Update"/> 
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
$('.input-group input').attr( "class", "form-control" );
$('#id_image').attr( "class", "fa fa-camera" );

$("#id_image").change(file_display (id='#id_image'));
    function file_display(id) {
    // --- event to display image thumbnail adjacent to file upload control.
    $(id).change(function() {
        var reader = new FileReader();
        var fileupload_element = $(this);
        reader.onload = function(event) {
            var ext = $(id)[0].files[0].name.split('.').pop();
            var file_name = $(id)[0].files[0].name;

            if (file_name.length >= 15) {
                file_name = file_name.substring(0, 15) + '...'
            }
            var file_src = event.target.result
            var icon_class = ''
            var element_tag = '<span class="[[thumbnail_icon]]"></span>';
            var thumbnail_container = '<div class="thumbnail_container col-sm-4">[[element_tag]]<span>' +
                file_name + '</span><span class="close"></span></div>'

            switch (ext.toLowerCase()) {
                case "png":
                case "jpeg":
                case "bmp":
                case "gif":
                case "jpg":
                    element_tag = ' <img src="[[file_src]]" />'
                    break;
                case "pdf":
                    icon_class = 'fa fa-file-pdf-o fa-3x'
                    break;
                case "doc":
                case "docx":
                    icon_class = 'fa fa-file-word-o fa-3x'
                    break;
                default:
                    icon_class = 'fa fa-file fa-3x'
                    break;
            };

            thumbnail_container = thumbnail_container.replace('[[element_tag]]', element_tag);
            thumbnail_container = thumbnail_container.replace('[[file_src]]', file_src);
            thumbnail_container = thumbnail_container.replace('[[thumbnail_icon]]', icon_class);
            $(".thumbnail_container").remove()

            fileupload_element.parent().append(thumbnail_container);

            $(".thumbnail_container .close").click(function(e) {
                $(id)[0].value = '';
                $(this).parent().remove();
            });
        }
        reader.readAsDataURL($(id)[0].files[0]);
    });
}
</script>
{% endblock %}