accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
LoginView,
LogoutView,
PasswordResetView,
PasswordResetConfirmView,
PasswordResetDoneView,
PasswordResetCompleteView,
PasswordChangeView,
PasswordChangeDoneView,
)

from .views import edit_profile
from . import views

app_name = "accounts"
urlpatterns = [
    url(r'settings/accounts/$', views.accounts_settings, name='accounts_settings'),
    url(r'settings/general/$', views.general_settings, name='general_settings'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': '/accounts/login'}, name='logout'),
    url(r'^user/profile/$', views.profile, name='Profile'),
    url(r'^user/profile/friend/(?P<pk>.+)/$', views.friend_profile, name='Friend_Profile'),
    url(r'^user/profile/add/$', views.add_user_info, name='add_user_info'),
    url(r'^user/profile/update/$', views.update_user_info, name='update_user_info'),
    url(r'^profile/edit/$', views.edit_profile, name='Profile-update'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^password-reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password-reset/complete/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^activate/(?P<uidb64>.+)/(?P<token>.+)/$', views.activate, name='activate'),
    url(r'connect/(?P<operation>.+)/(?P<pk>.+)/$', views.change_friend, name='change_friend'),
]

home/urls.py
from django.conf.urls import url
from .api import views as api_views
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$',  views.index, name='home'),
    url(r'^test/$',  views.test, name='home'),
    url(r'^feedback/$',  views.feedback, name='feedback'),
    url(r'^question/$',  views.question_upload, name='question_upload'),
    url(r'^about/$',  views.about, name='about'),
    url(r'^Members/$',  views.members, name='members'),
    url(
        regex=r'^api/get-username/$',
        view=api_views.get_username,
    ),
    url(
        regex=r'^api/userlist/$',
        view=api_views.get_user_list,
    ),
    url(
        regex=r'^api/userprofile/$',
        view=api_views.get_user_profile,
    ),
    url(
        regex=r'^api/event-list/$',
        view=api_views.get_events,
    ),
    url(
        regex=r'^api/current-user-detail/$',
        view=api_views.current_user_detail,
    ),
    url(
        regex=r'^api/userprofile/(?P<pk>\d+)/$',
        view=api_views.get_user_profile,
    ),
]
   

skflite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls import url
from home import views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('home.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'social/', include('social.urls', namespace = "social")),
    path('admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf.urls import url
from . import views
app_name = "social" 
urlpatterns = [
    url(r'^Post/$',  views.user_post, name='post'),
    url(r'^Post/delete/(?P<pk>[0-9]+)$',  views.delete_post, name='delete_post'),
    url(r'^Event/$',  views.events, name='events'),
    url(r'^Event/delete/(?P<pk>[0-9]+)$',  views.delete_events, name='delete_events'),
    url(r'^News/$',  views.news, name='news'),
   
]
    

home/models.py
from django.db import models

class Subject(models.Model):
    subject_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subject_name

SUBJECT_OPTIONS =(
       ('', 'Unknown'),
       ('Python', 'Python'),
       ('Django', 'Django'),
       ('Angular', 'Angular'),
    )
class Question(models.Model):
    Subject_name = models.CharField(max_length=255, choices=SUBJECT_OPTIONS)
    question = models.CharField(max_length=100)
    image = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.question
    

home/forms.py
from django import forms
from .models import Question
from .widgets import CustomSelectWidget

class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    comments = forms.CharField(required=False, widget=forms.Textarea(
        attrs={'rows': 4, 'cols': 40, 'placeholder': 'Comments'}))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('Subject_name', 'question', 'image' )
        labels = {
            'Subject_name': 'Select subject',
            'question': 'Enter question',
            'image': 'Attech file'         
        }
        help_texts = {
            'Subject_name': 'Please select subject that we can explain better',
            'question': 'Mention question detail',
            'image': 'Attech image, doc if anny'
        }
        widgets = {
            'Subject_name': CustomSelectWidget,       
        }

class ReviewForm(forms.Form):
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    comments = forms.CharField(widget=forms.Textarea, required=True)


class ScrapyForm(forms.Form):
    url = forms.URLField(required=True)
    element = forms.CharField(required=True)

home/api/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from rest_framework.decorators import api_view
from social.models import Event
from accounts.models import Friend, Profile



@api_view()
def get_username(request):
    username = request.GET.get('username', '')
    users = User.objects.filter(username=username)

    username = []
    for item in users:
        username.append({'username': item.username,})
    data = {
        'username': username,
    }
    return JsonResponse(data)


@api_view()
def get_user_list(request):
    users = User.objects.all()
    user_list = []
    for item in users:
        user_list.append({'username': item.username, 'slug': item.email})
    data = {
        'user_list': user_list,
    }
    return JsonResponse(data)

@api_view()
def get_user_profile(request, pk=None):
    if pk:
        users = User.objects.filter(pk=pk)
    else:
        users = User.objects.filter(username=request.user)
    user_profile = []
    for item in users:
        user_profile.append({'username': item.username, 'email': item.email, 'Name':item.first_name})
    data = {
        'user_profile': user_profile,
    }
    return JsonResponse(data)

@api_view()
def get_events(request):
    event = Event.objects.all()
    events = []
    for item in event:
        events.append({'title': item.title, 'start': item.start_date, 'end': item.end_date, 'backgroundColor': item.event_class})
    data = {
        'events': events,
    }
    return JsonResponse(data)

@api_view()
def current_user_detail(request):
    profile = User.objects.filter(username=request.user)
    profile_detail = []
    for item in profile:
        profile_detail.append({'first_name': item.first_name, 'last_name': item.last_name, 'email': item.email, 'id':item.id})

    user_info = Profile.objects.filter(user=request.user)
    print(user_info)
    for item in user_info:
        profile_detail.append({'profession': item.profession, 'skils': item.skils, 'education': item.education, 'bio': item.bio, 'location': item.location, 'email': item.birth_date})
    
    if (Friend.objects.filter(current_user=request.user)).exists():
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
        friend = []
        for item in friends:
            friend.append({'first_name': item.first_name, 'last_name': item.last_name, 'pk':item.pk})
    else:    
        friend = []
    data = {
        'profile_detail': profile_detail,
        'friend': friend,
    }
    return JsonResponse(data)

home/views.py
import socket

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import BadHeaderError, EmailMessage, send_mail
from django.shortcuts import HttpResponse, redirect, render
from django.views.generic import TemplateView

import requests
from accounts.models import Friend
from bs4 import BeautifulSoup
from skflite import settings
from social.forms import UserPostForm
from social.models import UserPost

from .forms import ContactForm, QuestionForm, ReviewForm, ScrapyForm
from .models import Question, Subject


def handler404(request):
    return render(request, '404.html', status=404)

def handler500(request):
    return render(request, '500.html', status=500)


@login_required
def test(request):


    # client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # server_address = ('localhost', 10000)
    # client.bind(server_address)
    # #streamurl = '(ws://streamer-bin.tdameritrade.com)'
    # # ip = socket.getaddrinfo ("ws://echo.websocket.org/", 80)
    # con = client.connect(("127.0.0.1",10000))
    # con.send('thanks')
    #addreinfo = socket.getaddrinfo('localhost', 8000)
    if request.method == 'POST':
        form = ScrapyForm(request.POST)
        if form.is_valid(): 
            url = form.cleaned_data['url']
            element = form.cleaned_data['element']  
            page = requests.get(url)
            soup = BeautifulSoup(page.content, 'html.parser')
            p=soup.find(element)
            s=soup.find_all(class_=""+element+"")
            return HttpResponse(s)                                                                 
    else:
        form = ScrapyForm()
    return render(request, "test.html", {
        'form': form
    })
    

@login_required
def index(request):
    if request.method == 'POST':
        form = UserPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.posted_by = request.user
            post.save()
    else:
        form = UserPostForm()
    if(Friend.objects.filter(current_user=request.user, status=True)).exists():
        friend = Friend.objects.get(current_user=request.user )
        friends = friend.users.all()
    else:
        friends=[]
    context = {
    'form': form,
    'Friends': friends,
    'Post': UserPost.objects.all(),
    }
    return render(request, "home.html", context)

@login_required
def about(request):
    return render(request, "about.html")

@login_required
def members(request):
    context = {
    'members': User.objects.exclude(id=request.user.id),
    }
    return render(request, "members.html", context)

def question_upload(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = QuestionForm()
    return render(request, 'home/Question_upload.html', {
        'form': form
    })

@login_required
def feedback(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            print('form valid')
            subject = 'Feedback from site'
            html_content = (
                '<h4>You have received a new message from the contact us form on your website</h4><br/>'
                '<strong>Email: </strong>' + form.cleaned_data['email'] + '<br/>'
                '<strong>Phone: </strong>' + form.cleaned_data['phone'] + '<br/>'
                '<strong>Comments: </strong>' + form.cleaned_data['comments'] + ''
            )
            from_email = settings.EMAIL_HOST_USER
            to = [settings.ADMINS[0][1]]
            print(to)
            print(from_email)
            try:
                msg = EmailMessage(subject, html_content, from_email, to)
                msg.content_subtype = "html"
                msg.send()
                print('message send')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
        else:
            return redirect('/feedback')  
    else:
        form = ReviewForm()
    return render(request, 'feedback.html', {'form': form})

templates/about.html
{% load static %}
<script src="{% static "/angular/angular.js" %}" type="text/javascript"></script>
<script src="{% static "/angular/custom-angular.js" %}" type="text/javascript"></script>

<div ng-app="myApp" ng-controller="myCtrl"> 

        <p>Today's welcome message is:</p>
        
        <h1>{{myWelcome}}</h1>
        
        </div>
        
        
        <script>
        var app = angular.module('myApp', []);
        app.controller('myCtrl', function($scope, $http) {
          
              $scope.myWelcome = "shadmaan";
         
        });
        </script>

      

templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/contact.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<img src="{% static "Images/images.jpg" %}" alt="My image"/>
<p>You can change the size of a heading with the style attribute, using the font-size property.</p>


{% endblock %}








{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <title>Bootstrap Theme Company Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <link rel="stylesheet" href="{% static "css/layout.css" %}">
  <link rel="stylesheet" href="{% static "css/custom.css" %}">

</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar">bxvb</span>
        <span class="icon-bar">cxbv</span>
        <span class="icon-bar">xbcbv</span>                        
      </button>
      <a class="navbar-brand" href="#myPage">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">HOME</a></li>
        <li><a href="/about">ABOUT</a></li>
        <li><a href="/question">PORTFOLIO</a></li>
        <li><a href="#pricing">PRICING</a></li>
        <li><a href="/contact">CONTACT</a></li>
        <li><a href="/accounts/logout/">LOGOUT</a></li>
        {% if not request.user.is_authenticated %}
        <li><a href="/accounts/signup">SIGNUP</a></li>
        <li><a href="/accounts/login">LOGIN</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  {% block content %}
  {% endblock %}
</div>

<footer class="container-fluid text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>Bootstrap Theme Made By <a href="https://www.w3schools.com" title="Visit w3schools">www.w3schools.com</a></p>
</footer>
</body>
</html>

      

templates/contact_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>contact</h1>
{{ flatpage.title }}
  <div>
    {{ flatpage.content }}
  </div>

{% endblock %}

templates/email.html
<!-- templates/email.html -->
<h1>Contact Us</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>

templates/feedback.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="addthis_inline_share_toolbox">
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-595caeea2a4fbf50"></script>
  </div>
<div class="content">
    <div class="box box-success">
        <div class="custom-container">
            <div class="row">
                <div class="col-sm-12 shadow" style="box-shadow:0px 0px 5px 0px">
                    <h1>Feedback</h1>
                    <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-actions">
                    <button type="submit">Send</button>
                    </div>
                    </form>
                </div>
            </div>  
        </div>    
    </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<section class="content">
  <div class="row">
    <div class="col-sm-9">
      <!-- ----------------------------------------------Post form----------------------------------------------------------- -->
      <div class="box box-success">           
        <div class="box-header with-border">
          <h3 class="box-title">Write somthing here</h3>
        </div>
        <div class="box-body">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <div class="col-md-2 co-sm-2">
                {% if user.profile.image %}
                <img src="/media/{{user.profile.image}}" width="50" height="50" class="img-circle" alt="User Image"/>
                {% else %}       
                <img src="/media/user/default_male.PNG" width="50" height="50" class="img-circle" alt="User Image"/>
                {% endif %}
              </div>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-md-8 col-sm-8">
                  {{ form.user_post_description }}                                            
                </div>
                <div class="col-md-2 col-sm-2">
                  <button class="btn btn-success" type="submit">POST</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-----------------------------------------USER POST------------------------------------------------------>
      <div class="box box-info">
        <div class="box-body">
          {% for p in Post %}
            <div class="box box-widget">
              <div class="box-header with-border">
                <div class="user-block">
                  <img class="img-circle" src="/static/Images/user2-160x160.jpg" alt="User Image">
                  <span class="username"><a href="#">{{p.posted_by}}</a></span>
                  <span class="description">Shared publicly - {{p.posted_date}}</span>
                </div>                  
                <div class="box-tools">
                  <div class="btn-group">
                    <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <i class="fa fa-align-right"></i>                   
                    </button>
                    <ul class="dropdown-menu" style="right: 0;" role="menu">
                      <li><a href="#">Action1</a></li>
                      <li><a href="#">Action1</a></li> 
                      {% if p.posted_by == request.user%}         
                      <li class="divider"></li>                
                      <li><a href="{% url 'social:delete_post' p.pk %}">Delete</a></li>
                      <li><a href="{% url 'social:delete_post' p.pk %}">Edit</a></li>
                      {% endif %}
                    </ul>
                  </div>
                  
                </div>
              </div>     
              <div class="box-body">
                {{ p.user_post_description|safe }}              
                <button type="button" class="btn btn-default btn-xs"><i class="fa fa-share"></i> Share</button>
                <button type="button" class="btn btn-default btn-xs"><i class="fa fa-thumbs-o-up"></i> Like</button>
                <span class="pull-right text-muted">127 likes - 3 comments</span>
              </div>
              <div class="box-footer box-comments">
                <div class="box-comment">                     
                  <img class="img-circle img-sm" src="/static/Images/user2-160x160.jpg" alt="User Image">    
                    <div class="comment-text">
                      <span class="username">
                        Maria Gonzales
                        <span class="text-muted pull-right">8:03 PM Today</span>
                      </span>
                        It is a long established fact that a reader will be distracted
                        by the readable content of a page when looking at its layout.
                    </div>
                </div>                   
              </div>
              <div class="box-footer">
                <form action="#" method="post">
                  <img class="img-responsive img-circle img-sm" src="/static/Images/user2-160x160.jpg" alt="Alt Text">                  
                    <div class="img-push">
                        <input type="text" class="form-control input-sm" placeholder="Press enter to post comment">
                    </div>
                </form>
              </div>        
            </div>
          {% endfor %}  
        </div>
        <div class="box-footer clearfix">
          <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat">View All Post</a>
        </div>       
      </div>    
    </div>
    <div class="col-sm-3">  
      <!-- -----------------------------------------Friends LIST -------------------------------------------------------->
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Friends</h3>        
          <div class="box-tools pull-right">
            <span class="label label-danger">{{ Users|length }} New Members</span>
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
            </button>
          </div>
        </div> 
        <div class="box-body friend_list"> 
          <table>
              {% for list in Friends %}           
            <tr>
              <td><img src="static/Images/avatar5.png" width="50" height="50" class="img-circle" alt="User Image"/></td>
              <td><a href="{% url 'accounts:Friend_Profile' pk=list.pk %}"><h3>{{ list.first_name }}</h3></a></td>
            </tr>  
            {% endfor %}   
          </table>                    
        </div>
        <div class="box-footer text-center">
          <a href="javascript:void(0)" class="uppercase">View All Users</a>
        </div>
      </div>     
    </div>
  </div>
</section>
{% endblock %}

templates/members.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="content">
  <div class="box">
      <div class="row">
          <div class="col-sm-10">
            <ul> 
                {% for list in members %}                                  
                <li>             
                  <h3 class="users-list-name" href="#">{{ list.username }}</h3>
                </li>
                <a href="{% url 'accounts:change_friend' operation='add' pk=list.pk %}">
                    <button type="button" class="btn btn-success">Add friend</button>
                </a>
                <a href="{% url 'accounts:change_friend' operation='remove' pk=list.pk %}">
                    <button type="button" class="btn btn-denger">Remove friend</button>
                </a>
                <a href="{% url 'accounts:change_friend' operation='conform' pk=list.pk %}">
                    <button type="button" class="btn btn-denger">Accept friend</button>
                </a>
                {% endfor %}     
              </ul>
          </div>
        </div>
  </div>
</div>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content">
    <div class="box box-success">
        <div class="custom-container">
            <div class="row">
                <div class="col-sm-12 shadow" style="box-shadow:0px 0px 5px 0px">
                    <form method="post">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}"> {{ form.url.label }}</label>
                        <div>{{form.url}}</div> 
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}"> {{ form.element.label }}</label>
                        <div>{{form.element}}</div> 
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="btn btn-block btn-info btn-flat" value="Parse"/>
                    </div>
                    </form>
                </div>
            </div>  
        </div>    
    </div>
</div>
<script>
    $('input').addClass('form-control');
</script>
{% endblock %}